# Input — adjust kb_layout for your keyboard
input {
  kb_layout = us
  sensitivity = 0
  accel_profile = flat

  repeat_rate = 45
  repeat_delay = 300

  follow_mouse = 1

  touchpad {
    natural_scroll = true
    clickfinger_behavior = true
  }
}
