# Input — adjust kb_layout for your keyboard
input {
  kb_layout = no
  sensitivity = 5
  accel_profile = flat #adaptive

  repeat_rate = 45
  repeat_delay = 300

  natural_scroll = true
  scroll_factor = 1.5
  follow_mouse = 1

  touchpad {
    natural_scroll = true
    clickfinger_behavior = true
  }
}
