# Window rules
windowrule = suppress_event maximize, match:class .*
windowrule = tag +default-opacity, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# No border on Brave
windowrule = border_size 0, match:class brave-browser

# Float TUI tools
windowrule = float on, match:class tui.impala
windowrule = center on, match:class tui.impala
windowrule = size 600 400, match:class tui.impala

windowrule = float on, match:class tui.bluetui
windowrule = center on, match:class tui.bluetui
windowrule = size 600 400, match:class tui.bluetui

# Wallpaper picker
windowrule = float on, match:class tui.wallpaper
windowrule = center on, match:class tui.wallpaper
windowrule = size 1400 850, match:class tui.wallpaper
