#!/bin/bash

# Cycles through the background images available
# Override: uses swww instead of swaybg

THEME_NAME=$(cat "$HOME/.config/omarchy/current/theme.name" 2>/dev/null)
THEME_BACKGROUNDS_PATH="$HOME/.config/omarchy/current/theme/backgrounds/"
USER_BACKGROUNDS_PATH="$HOME/.config/omarchy/backgrounds/$THEME_NAME/"
CURRENT_BACKGROUND_LINK="$HOME/.config/omarchy/current/background"

mapfile -d '' -t BACKGROUNDS < <(find -L "$USER_BACKGROUNDS_PATH" "$THEME_BACKGROUNDS_PATH" -maxdepth 1 -type f -print0 2>/dev/null | sort -z)
TOTAL=${#BACKGROUNDS[@]}

if (( TOTAL == 0 )); then
  notify-send "No background was found for theme" -t 2000
  swww img --color '#000000' --transition-type none
else
  # Get current background from symlink
  if [[ -L $CURRENT_BACKGROUND_LINK ]]; then
    CURRENT_BACKGROUND=$(readlink "$CURRENT_BACKGROUND_LINK")
  else
    CURRENT_BACKGROUND=""
  fi

  # Find current background index
  INDEX=-1
  for i in "${!BACKGROUNDS[@]}"; do
    if [[ ${BACKGROUNDS[$i]} == $CURRENT_BACKGROUND ]]; then
      INDEX=$i
      break
    fi
  done

  # Get next background (wrap around)
  if (( INDEX == -1 )); then
    NEW_BACKGROUND="${BACKGROUNDS[0]}"
  else
    NEXT_INDEX=$(((INDEX + 1) % TOTAL))
    NEW_BACKGROUND="${BACKGROUNDS[$NEXT_INDEX]}"
  fi

  # Set new background symlink
  ln -nsf "$NEW_BACKGROUND" "$CURRENT_BACKGROUND_LINK"

  # Display with swww
  swww img "$CURRENT_BACKGROUND_LINK" --transition-type fade --transition-duration 1
fi
