#!/bin/bash

# Launch the TUI command passed in as an argument in kitty with an org.omarchy.COMMAND app id for styling.

exec setsid uwsm-app -- kitty --app-id=org.omarchy.$(basename $1) -e "$1" "${@:2}"
