context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "User EQ"
            media.name = "User EQ"
            filter.graph = {
                nodes = [
                    {
                        type = builtin
                        name = eq_highshelf_L
                        label = bq_highshelf
                        control = { "Freq" = 500.0 "Q" = 0.7 "Gain" = 0.0 }
                    }
                    {
                        type = builtin
                        name = eq_highshelf_R
                        label = bq_highshelf
                        control = { "Freq" = 500.0 "Q" = 0.7 "Gain" = 0.0 }
                    }
                ]
                links = []
                inputs  = [ "eq_highshelf_L:In" "eq_highshelf_R:In" ]
                outputs = [ "eq_highshelf_L:Out" "eq_highshelf_R:Out" ]
            }
            capture.props = {
                media.class = Audio/Sink
                node.name = "user_eq"
                node.description = "User EQ"
                audio.channels = 2
                audio.position = [ FL FR ]
                state.default-volume = 1.0
            }
            playback.props = {
                node.name = "user_eq_output"
                audio.channels = 2
                audio.position = [ FL FR ]
                node.target = "alsa_output.platform-sound.pro-output-1"
                stream.dont-remix = true
                node.passive = true
            }
        }
    }
]
