# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size 11.0

# Window
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0
background_opacity 1.0

# Performance
repaint_delay 8
input_delay 1
sync_to_monitor no

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
map super+v paste_from_clipboard
map super+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor
enable_audio_bell no

# Tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Scrollback
scrollback_lines 2000
wheel_scroll_min_lines 1

linux_display_server auto
